import type { PluginManifest } from './types.js'

export const plugin: PluginManifest = {
  name: 'git',
  version: '1.0.0',
  description: 'Git aliases (ported from oh-my-zsh)',
  aliases: {
    g: 'git',
    ga: 'git add',
    gaa: 'git add --all',
    gapa: 'git add --patch',
    gau: 'git add --update',
    gb: 'git branch',
    gba: 'git branch --all',
    gbd: 'git branch --delete',
    gbD: 'git branch --delete --force',
    gbl: 'git blame -w',
    gc: 'git commit --verbose',
    'gc!': 'git commit --verbose --amend',
    gca: 'git commit --verbose --all',
    'gca!': 'git commit --verbose --all --amend',
    gcam: 'git commit --all --message',
    gcb: 'git checkout -b',
    gcd: 'git checkout develop',
    gcm: 'git checkout main',
    gco: 'git checkout',
    gcp: 'git cherry-pick',
    gd: 'git diff',
    gds: 'git diff --staged',
    gdw: 'git diff --word-diff',
    gf: 'git fetch',
    gfa: 'git fetch --all --prune',
    gfo: 'git fetch origin',
    gl: 'git pull',
    glg: 'git log --stat',
    glog: 'git log --oneline --decorate --graph',
    gloga: 'git log --oneline --decorate --graph --all',
    gm: 'git merge',
    gma: 'git merge --abort',
    gp: 'git push',
    gpd: 'git push --dry-run',
    gpf: 'git push --force-with-lease',
    gpsup: 'git push --set-upstream origin $(git branch --show-current)',
    gr: 'git remote',
    gra: 'git remote add',
    grb: 'git rebase',
    grba: 'git rebase --abort',
    grbc: 'git rebase --continue',
    grbi: 'git rebase --interactive',
    grh: 'git reset',
    grhh: 'git reset --hard',
    grs: 'git restore',
    grss: 'git restore --staged',
    gss: 'git status --short',
    gst: 'git status',
    gsta: 'git stash push',
    gstaa: 'git stash apply',
    gstd: 'git stash drop',
    gstl: 'git stash list',
    gstp: 'git stash pop',
    gsts: 'git stash show --patch',
    gsw: 'git switch',
    gswc: 'git switch --create',
    gts: 'git tag --sign',
  },
}
